name: vllm

services:
  app:
    image: vllm/vllm-openai
    restart: unless-stopped
    ipc: host  # Required for efficient memory sharing in multi-process inference
    entrypoint: vllm serve --config /config.yml
    ports:
      - $APP_PORT:8000
    volumes:
      - ./data:/root/.cache/huggingface
      - ./configs/$CONFIG.yml:/config.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
